---
name: Xango
version: 1.05
author:
  - |-
    Copyright 2005 Daisuke Maki E<lt>dmaki@cpan.orgE<gt>. All rights reserved.
    Development funded by Brazil, Ltd. E<lt>http://b.razil.jpE<gt>
abstract: Event Based High Performance Web Crawler Framework
license: perl
requires:
  HTTP::Request: 0
  HTTP::Response: 0
  Log::Dispatch: 0
  POE: 0
  YAML: 0
build_requires:
  Test::More: 0
provides:
  Xango:
    file: lib/Xango.pm
    version: 1.05
  Xango::Broker:
    file: lib/Xango/Broker.pm
  Xango::Broker::Base:
    file: lib/Xango/Broker/Base.pm
  Xango::Broker::Pull:
    file: lib/Xango/Broker/Pull.pm
  Xango::Broker::Push:
    file: lib/Xango/Broker/Push.pm
  Xango::Config:
    file: lib/Xango/Config.pm
  Xango::Job:
    file: lib/Xango/Job.pm
generated_by: Module::Build version 0.2612
